# Generated by Django 2.1.8 on 2019-11-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_lv',
            new_name='user_grade',
        ),
    ]
